version: '3.8'
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: ORACLE123*
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle19c-data:/opt/oracle/oradata
    restart: always

volumes:
  oracle19c-data:
    driver: local

